openapi: 3.0.1
info:
  title: product
  version: "0.1"
paths:
  "/products":
    get:
      summary: We need to return all product to end user
      description: This method get all product
      operationId: getAllProducts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductResponse"
        "4XX":
          description: Can't find any product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      operationId: createProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductResponse"
      responses:
        "200":
          description: Created Successful
        "4XX":
          description: bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  "/products/{id}":
    summary: Get single product from list of products
    description: To get single product
    get:
      operationId: getProductById
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductResponse"


components:
  schemas:
    ProductResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Cup
        price:
          type: number
          minimum: 5
          example: 55.0
        isInStock:
          type: boolean
          example: true

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          example: 405
        description:
          type: string
          example: server error
